### ISSUE TITLE
Add all misssing import 

### ISSUE THREAD

**Issue by Code-Undefined** [FallenMax/styled-components-extractor#4]
hi , to use this  plugin .
I want to new how to use  Add all misssing import  like you show us.
I can not see this options.
Thanks

**Comment by FallenMax** [comment]
@Code-Undefined Hi, that feature is provided by TypeScript and VSCode itself. As long as you are using TypeScript, VSCode will suggest missing imports when you right-click variables to be imported.

I'm not sure if VSCode support auto-import with JavaScript though. Hope it helps!

**Comment by Code-Undefined** [comment]
Ok,  thanks for your reply!  And i will upgrade to use TS in future projects.
