### ISSUE TITLE
Interested in some additional functionality?

### ISSUE THREAD

**Issue by abrindam** [FallenMax/styled-components-extractor#5]
Hi, for my own personal use, I forked this repository recently and added some new functionality:

- **Extract components directly into the same file**. Skips the clipboard and just adds the extracted components to the bottom of the file they were extracted from.
- **Extract components into a separate file**. The user sets preferences to determine the name of the file the components will be extracted into, e.g `{filename}.styles.ts`. Skips the clipboard and adds the extracted components to the bottom of the separate file. Automatically adds an import for the new components to the file the components were extracted from.

I really loved the idea of this extension and I wanted to take it further.

I'd be happy to contribute these changes back to this repository, if you're interested. My changes only add functionality so they should be backwards compatible. Let me know and I'll open a PR!

**Comment by FallenMax** [comment]
@abrindam Thanks for your interest in contributing to the project. I like these new commands your proposed and I'm happy to review a pull request for it. Please go ahead and open a PR and I'll take a look as soon as I can. Thanks for your contribution!

**Comment by abrindam** [comment]
@FallenMax Awesome! Let me just clean up a few things, update the README, add tests, etc and I'll get you a PR in the next couple of days.

**Comment by abrindam** [comment]
@FallenMax I've opened a PR: https://github.com/FallenMax/styled-components-extractor/pull/6

As noted, I haven't updated the README yet - I figured we could fine-tune things in the PR before updating the documentation.

**Comment by FallenMax** [comment]
Closed by #6
